### ISSUE TITLE
not big on the blue and green color choice in fig10

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#14]
had to distinguiish.

somethingwith more contrast?

**Comment by rahlk** [comment]
@timm These colors ok?
![image](https://cloud.githubusercontent.com/assets/1433964/9430310/52bd6cc6-49be-11e5-97a9-807196eff647.png)
![image](https://cloud.githubusercontent.com/assets/1433964/9430392/0032de74-49c2-11e5-9677-2a71fabc5158.png)

**Comment by timm** [comment]
now the gray and black are hard to distinguish. 

what does red,green,lightblue,black look like?

oh- and the names are now:

DTREES = 4.XTREES
HOW = 3.BIC
kNN = 1.CD
kNN+FS = 2.CD+FS

**Comment by rahlk** [comment]
![image](https://cloud.githubusercontent.com/assets/1433964/9430525/6f72b23c-49c7-11e5-804e-81730cd4cf4a.png)
![image](https://cloud.githubusercontent.com/assets/1433964/9430528/8dac064a-49c7-11e5-89bc-e4bb7559f4c9.png)

**Comment by timm** [comment]
please do again.... 2 cols wide. see if that is any clearer.

please move the key to RHS so we save on the vertical whitespace

**Comment by rahlk** [comment]
Need access to lab computer. Will do this 1st thing tomo.

**Comment by timm** [comment]
no worries

**Comment by timm** [comment]
intelligently done.  minimal; real estate on the screen, one legend suffices for both plots. no need to make the lucene plot 100% wide.... 75% will do with a little space on the side for the other guy 

![image](https://cloud.githubusercontent.com/assets/29195/9450720/4d7970c4-4a78-11e5-9217-a9033a88bc37.png)

**Comment by rahlk** [comment]
10 4. Corel's magic :)
