### ISSUE TITLE
fix last sentence of abstract

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#16]
@rahlk !

make sure the text is up to date with the results.

last line of abstract is old and needs fixing.

WRONG:  runtimes to     72\%,75\%  (median) and 66\%,20\% (best case) of the initial values, respectively.

**Comment by timm** [comment]
any other "fossils" in the paper?

**Comment by rahlk** [comment]
there may be some fossils. I'll get rid of them right away.
