### ISSUE TITLE
who do i cite re the soruce of the sigmund config data?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#18]
should we call it the sigmund data or the guo data?

i.e. what is the soruce. is it....  [11] or juresk
ianmei Guo, Krzysztof Czarnecki, Sven Apel, NorbertSiegmund, and Andrzej Wasowski. Variability-awareperformance prediction: A statistical learning approach. InAutomated Software Engineering (ASE), 2013 IEEE/ACM28th I

**Comment by rahlk** [comment]
We should call it the Guo Data, of just Config data.

**Comment by timm** [comment]
will do

**Comment by timm** [comment]
what is the url for the config data?

**Comment by rahlk** [comment]
http://openscience.us/repo/performance-predict/cpm.html
