### ISSUE TITLE
Do we need HOW?

### ISSUE THREAD

**Issue by rahlk** [ai-se/XTREES#2]
@timm 
I think we should include HOW, as a case based reasoner, in our paper. It'd be great addition for a clear and a linear story. Thoughts?
1. Baseline 1: Clustering + kNN (k=1) + Deltas
2. Baseline 2: Clustering + kNN (k=1) + Deltas + Feature Selection
3. HOW (A CBR): Clustering + Contours (and slopes) + Deltas + Feature Selection
4. CART (A Model Based Approach): Decision trees + Deltas
5. XTREES (A Model Based Approach): WHERE + CART

[**See updated results**](https://github.com/ai-se/Transfer-Learning/wiki/Week-of-July-20th)

**Comment by timm** [comment]
above description looks good
