### ISSUE TITLE
add pointer to your source code

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#20]
? great a cleaned up version of your code in some other repo
? add your code as a sub-directory here

in either case, add that pointer to https://github.com/ai-se/XTREES/blob/master/README.md

**Comment by rahlk** [comment]
I have a repo at https://github.com/ai-se/Transfer-Learning/ it neatly organized. We can use that.

**Comment by rahlk** [comment]
Ok, I may have some residual files. I'll delete them.

**Comment by timm** [comment]
its a bit .... complicated. can you make the top lever dir something simpler? and can your readme include a howto get one little demo out of the whole thing? just as a starter?

**Comment by rahlk** [comment]
Will do

**Comment by timm** [comment]
can we drop in the pointer to the source code to the readme now? then at least that will done
