### ISSUE TITLE
clarification please

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#21]
in the current text
- It then looks for $C_j$, i.e. the  nearest centroid with a better performance score. The differences in the independent features  between these two clusters constitute the \textit{"contrast set"}. These contrast sets acts as plans that can be used to reflect over the test cases to improve them.

so, conceptual, we could pre-compute and cache all these contrast sets. and when a test instance arrives, we just offer a plan that is the pre-computed and cached contrast set?

**Comment by rahlk** [comment]
Yup, that's a possibility. It would work just as well.

**Comment by timm** [comment]
hey, i'm taking some shortcuts in the description of our instance-based methods. see the current doc sections 3.2, 3.3, 3.4. i know i'm skating over some of the lower-level details but
- it is unlikely our audience will appreciate those details
- given that our conclusions are "dont use methods 1,2,3" then i don't think there is any damage to the international research community if i skate that way

but see what you think. anything i really need to add back in?

**Comment by timm** [comment]
sorry, should have said 4.1, 4.2, 4.3

**Comment by rahlk** [comment]
Hey, I just went through the sections. It seems ok to me. In the description of BIC, we may want to add a note on our use of gradients to find plans.

**Comment by timm** [comment]
k
