### ISSUE TITLE
what's the performance score for the oo data sets?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#23]
f?
precision?
?

**Comment by timm** [comment]
dcant tell. must ask rahul

**Comment by rahlk** [comment]
Do you mean the ones on Figure 8? If so, it's the ratio of bugs after/before.

**Comment by timm** [comment]
1. number of examples with bug=0,1 
2. or number of bugs summed across all examples?

i'm thinking (1).

**Comment by rahlk** [comment]
You're right, it's the 1st case. The following ratio 

```
              number of bugs (>0) after 
performance = -------------------------
                 number (>0) before
```
