### ISSUE TITLE
rahu: having the devils own time with Figure1

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#24]
see what you can do... but we may beed to ping the shareltex help people on this. i've wasted HOURS on getting this pic to display.

perhaps im too tired and you can make it display straight away. 

or, perhaps recreate that figure, this time drawn for one column,

**Comment by rahlk** [comment]
Idk why, but sig-alternate doesn't respond to anything other than *.eps file. I was going nuts too! 
It's fixed now.

**Comment by rahlk** [comment]
Also, here's what I used to convert to eps - http://image.online-convert.com/convert-to-eps. I noticed that eps from gnuplot doesn't produce good quality graphs. So I use png followed by a tool called imagemagik `brew install imagemagick` to do this conversion.
