### ISSUE TITLE
does BIC (what we used to call HOW) do any feature selection?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#26]
looking at the times a certain feature requires to be changed, i'm saying probably not.

in which case i need to fix my description of BIC.

**Comment by rahlk** [comment]
I use feature weighting, same as CD but I do not prune features.

**Comment by timm** [comment]
reopen if if get this wrong: 

ferature weighing in the distance calcs.

**Comment by rahlk** [comment]
Feature weighting over the extent of mutation. Lower the fWeight, lower the extent of mutation.
