### ISSUE TITLE
why are we reporting on BIC?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#27]
method 1 and method2 i get--- they come from a prior paper.

but maybe we should just dump bic (HOW) all together?

comments? does it add anything to the rhetoric? does it teach us anything?

**Comment by rahlk** [comment]
Hey, please see #2. While writing I reasoned that using BIC would bridge CD, CD+FS, and XTREES. But I agree that it doesn't add anything to the rhetoric.

**Comment by timm** [comment]
slept on it

"HOW", now BIC, was used in the ase workshop paper. 

so that is why we are reporting BIC

**Comment by rahlk** [comment]
Speaking of which, Is there anything you want me to do for the camera ready submission?

**Comment by timm** [comment]
for the ase workshop paper?
- change all terms to XTREE and BIC.
- submit. you got the instuctions for that?

**Comment by rahlk** [comment]
Cool. I think the deltas graph needs to be changed as well.
