### ISSUE TITLE
what would be invoced making fig10 and fi11 all run 0 to 1

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#31]
right now, it looks like fig10's quartile changes are all on the same 0..1 scale but fig11 are all using their own internal min-max.

what's involved in getting fig11 to run min to max?

**Comment by rahlk** [comment]
I think both fig 10 and fig 11 use their internal min-max, for example ant's 0.22 is almost similar to ivy's 0.65. Would you like me to use a global min max instead?
