### ISSUE TITLE
limitation of training set

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#37]
“trust” in a model’s predictions are based on how far the test examples are from the training cloud. This is a valid assumption if the training set contains information representative of the current phenomenon you want to predict. Poor training set -> worthless predictions, so there needs to be some sort of post-hoc evaluation.

**Comment by rahlk** [comment]
the ccaveat here is "privoding the performance is adquate for that traaining set on that test"

new text . paster here==>

**Comment by rahlk** [comment]
**New Text**
- The quality of the prediction depends on the nature of the training data. Thus, we strongly recommend that both data set and the predictor be assessed prior to planning. This ensures that the predictor's performance is adequate for a data set. We tackle this issue in detail in \tion{tesd}.
