### ISSUE TITLE
more explanation needed of Jurezcko defect counts

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#38]
Sec 3: “For the most part, the methods of this paper treat the Jureczko as a discrete class data set, where defects are true if the raw defect count is greater than zero.” If you’re going for realism, telling me there are no defects in a class is not real. More explanation is needed for how # defects/class was determined by Juresczko. If I am doing planning, I care about defect severity, not bug counts.

**Comment by timm** [comment]
Not with you lucas. Severity is a hard nut to record

**Comment by llayman** [comment]
Severity is not hard to record, but it's hard to compare across projects.

The main point is that you need to explain the implications of data where every class either has zero or non-zero defects. To do that, you need to explain how the defects are identified. This is missing from the paper.

Looking at the study: XTREEs tells you a plan for changing OO metrics to improve from defects to no defects. If the defects reported are post-release customer defects, then fine. But if these are defects found by some test suite provided in the repo itself, then the planning implications are something totally different.
