### ISSUE TITLE
Figure 6

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#40]
- [ ] Fig 6: What are you learning? I assume which classes are defective.
- [ ] Fig 6: justify why “good” is recall > 60%, false alarm < 40%
- [ ] Fig 6: what is tuning?
- [ ] Fig 6: 4 “good” rows, 4 “neutral” rows, 3 “bad” rows. Seems like you need better learner selection. If the goal is planning, I don’t care what learner you use – I want the one that gives me the best (most accurate) planning results.

**Comment by timm** [comment]
As to why 60,40 as we read the mining software repositories literature, these are the levels reported as acceptable in that community. Note that several of our results exceed that standard.

**Comment by llayman** [comment]
Acceptable by whom? That's kind of a silly baseline. if I am doing planning, and you've got 40% false alarm, you could be talking about a huge amount of wasted refactoring effort.

I think the solution is just discuss the numbers rather than making a claim about good/bad.

**Comment by rahlk** [comment]
replace good bad with something low key like "majoirty correct"

dont say good bad

paste new text ==>

**Comment by rahlk** [comment]
**New Text:**

As a preliminary study, we split the Jureczko  data into train and test groups.
Random Forests (again, from the SciKit learn kit~\cite{Pedregosa2012}) were
built from the training data, then applied to the test data.
The "untuned'' columns of \fig{j} shows those results. We call a data set "usable'' if Random Forest is able to classifiy majority it of the instances correctly.
For this purpose, we set a threshold of $\mathit{pd}\ge 60 \wedge \mathit{pf} \le 30$\%
to select these data sets. With this threshold, however, none of our data sets would be suitable for this study.
