### ISSUE TITLE
•	Justify 50/50 split from training/testing instead of other methods (e.g., 10fold crossvalidation)

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#43]

**Comment by rahlk** [comment]
We do a 2-fold crossval.

**Comment by rahlk** [comment]
**Justification (Section 5.1.4, bullet 1):**
For Siegmund data, we performed a k-fold cross validation.Given the relatively smaller sample sizes in Apache and BDBJ,we chose k= 2. This, we reasoned, would maintain a sufficiently large test data size in order for R to be measuredreliably. However, in 2-fold cross validation, the divisionof data tends to affect the outcome significantly. To counterthis, we randomized the order of the data, training on one half while identifying treatment plans on the remaining test data, repeating the process 40 times as mentioned above.
