### ISSUE TITLE
further explanation of training and test sets in Section 5

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#44]
Sec 5.1: 50/50 split on data again for training and testing predictors and planners. Are the training sets taken from the whole data sets from Jurezcko, i.e., version N, N-1, N-2, etc? It seems to me that you would want to train on {N-1, N-2, … 1} and test on N. Maybe you do that but I missed it

**Comment by rahlk** [comment]
type in what you added here==>

**Comment by rahlk** [comment]
Training and testing sets are defined in Fig 6 for Jureczko data.
