### ISSUE TITLE
Expressing performance

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#46]
Generally a higher performance is expressed as a higher value, so in the report tables I would suggest reporting % reduction (e.g., 35%) instead of the new median (65%)

**Comment by timm** [comment]
It would look better with our better methods getting larger nums

Rahul, can do? Make our quartile 1 - after/before?

**Comment by rahlk** [comment]
also, there is some text where we define "R" in fig 9
![image](https://cloud.githubusercontent.com/assets/1433964/9472055/11138922-4b21-11e5-83dc-cc4ebc89ab7c.png)

**Comment by rahlk** [comment]
see #52
