### ISSUE TITLE
Not convinced of succinct and surprising

### ISSUE THREAD

**Issue by amarcusgit** [ai-se/XTREES#48]
This is a quick reaction, before my coffee and before reading the paper in detail.

The paper states that shorter plans are faster to implement - this is an unproven hypothesis. We have no evidence to support and I am not even sure it is true. It depends on the combinations of metrics in the plans. Also, it says nothing about the feasibility of changes to achieve such plans. For example, a plan may recommend reducing LOC (as later in the luscene example), but that will come at the expense of changing a multitude of other properties in unknown way.

As for surprising, I have doubts too. XTREE recommends reducing LOC and WE (the readers) know that this means a likely increase in coupling. However, XTREE does not "know" about the relationship between LOC and coupling, so this is not really surprising, but rather accidental.

**Comment by rahlk** [comment]
comment at end of validity. working with industrial partners to assess the feasility of our changes. at this state, zip to report.

paste in your new text here ==>

**Comment by rahlk** [comment]
**New Text (manuscript section 6.4):**
It is important to also explore the general practicality of the plans. To this end, we are currently undertaking is a `\textit{feasibility study}` collaboration with industrial partners to assess the general feasibility of our changes. With this study, we would like to understand the nature of changes suggested by XTREE. Specifically: are the changes proposed by XTREE small enough to be easily implemented on software projects? Also, are the changes large enough to be feasible? In other words, we are asking if users can sufficient fine-grained control to make the changes proposed in `\fig{changed}`.

**Comment by timm** [comment]
a little too much negative fuel for the reviewers. 

how about switching

> Specifically: are the changes proposed by XTREE small enough to be easily implemented on software projects? Also, are the changes large enough to be feasible? In other words, we are asking if users can sufficient fine-grained control to make the changes proposed in \fig{changed}.

to

For example, we want to check if programmers are willing to implement the  changes proposed by XTREE or are there other forces (e.g. social, psychological)  that might block a team from accepting the advice of an outside oracle like XTREE.   Note this a concern not just issues for XTREE, but for any tool proposing refactorings.
