### ISSUE TITLE
ASE Review Summary

### ISSUE THREAD

**Issue by rahlk** [ai-se/XTREES#5]
#### Reviewer 1
- [x]  Main thing: needs a thorough re-org
  -  I can see this... imagine pages 2 to 4 walk thru the different designers arguing why one improve the last
- [x] Code figures: REMOVE!
- [x] Clear research progression (we have this... see issue #2)
- [x] Include a brief paragraph on how each system works.
- [ ] Move primary contributions to Intro
- [x] Describe intuitions on how/why things work
- [x] Figures and their descriptions on the same page (clearer descriptions)
#### Reviewer 2
- [x] What changes are suggested? (done... see issue [#26](https://github.com/ai-se/Transfer-Learning/issues/26))
- [ ] Why LLVM and SQL don't perform as well?
- [x] any surprises?  The quality metrics in Figure 6 are generic. It seems that without using HOW, one would want to improve software quality metrics, which are aimed by the tool. It is more convincing if the authors could show the cases where HOW could point to an action that is not generally viewed as a good action for software maintenance, however, it would in fact reduce the defects. The actions such as splitting a large file, refactoring, are generic that one would need to do anyway.
  - Usual recommendation is to increase cohesion and reduce coupling
  - We got any data sets with the REVERSE recommendation?
  - And can we show that if we apply the usual recommendation, we f*ck up? get worse defects?
#### Reviewer 3
- [ ]  Similar issues as above...

**Comment by timm** [comment]
BIG sigh of relief... no one pinged the general approach to eval  . weight off my mind.

**Comment by rahlk** [comment]
Yeah! However, reviewer 2 suggested that we look at What-if analysis.
[Bird, Zimmermann - Assessing the Value of Branches with What-if Analysis.pdf](https://github.com/ai-se/XTREES/files/1133/Bird.Zimmermann.-.Assessing.the.Value.of.Branches.with.What-if.Analysis.pdf)

**Comment by timm** [comment]
in the above... we tick things when they are in the paper... not before

**Comment by timm** [comment]
for a grant i am writing, i need an answer to reviewer2, the "any surprises" dot point

**Comment by rahlk** [comment]
Basically, in BDBJ HOW performs better than CART. In SQL they all perform equally bad. In the rest, XTREEs and CART are always better. Please see https://github.com/ai-se/Transfer-Learning/wiki/Week-of-July-20th for reference.

**Comment by timm** [comment]
you are not reading the issue:

Usual recommendation is to increase cohesion and reduce coupling
We got any data sets with the REVERSE recommendation?
And can we show that if we apply the usual recommendation, we f*ck up? get worse defects?

**Comment by rahlk** [comment]
My bad, I thought reverse recommendations meant data sets where using XTREES was not a good idea.

My deltas chart are showing %change as a histogram, they answer what is being changed and how often. 

To answer this question I'm going to generate new charts that show magnitude and direction, I've opened a new issue for this [#45](https://github.com/ai-se/Transfer-Learning/issues/45)

**Comment by timm** [comment]
note you don't need N charts on N datasets

just one result on one data set.
