### ISSUE TITLE
Our ground truth model is POM3

### ISSUE THREAD

**Issue by rahlk** [ai-se/XTREES#51]
We do not use COCOMO, we use POM3's cost and completion -> #13

**Comment by timm** [comment]
here's some text on pm3. adjust as you need to

The POM3 model [46], [47] is a tool for exploring that management challenge. POM3 implements the Boehm and Turner model of agile programming [48] where teams select tasks as they appear in the scrum backlog. POM3 can study the implications of different ways to adjust task lists in the face of shifting priorities. The model outputs estimates  task completion rates; programmer idle rates; and total overall cost. POM3 represents requirements as a set of trees. POME3 models requirements as a dependency tree. A single requirement in the tree of a prioritization value and a cost, along with a list of child-requirements and dependencies. Before any requirement can be satisfied, its children and dependencies must first be satisfied. POM3 simulates changing priorities by making teams aware of random items in the requirements tree at random intervals, thus forcing teams to constantly readjust their "to do" lists. For further details on this model see [46], [47], [48]. 

46] D. Port, A. Olkov, and T. Menzies, “Using simulation to investi- gate requirements prioritization strategies,” in Proc. IEEE/ACM Int. Conf. Autom. Softw. Eng., 2008, pp. 268–277.
[47] B. Boehm and R. Turner, “Using risk to balance agile and plan- driven methods,” Computer, vol. 36, no. 6, pp. 57–66, Jun. 2003.
[48] B. Boehm and R. Turner, Balancing Agility and Discipline: A Guide for the Perplexed. Boston, MA, USA: Addison-Wesley, 2003.
