### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#53]
paper still has 100 typos. come on! don't let my attention deficit disorder scuttle the paper.

**Comment by rahlk** [comment]
It'll be done today. Promise!

**Comment by timm** [comment]
**all**  issues please. good to have a day or two to check the "final" version

**Comment by rahlk** [comment]
- [ ] kill orpahans #55

**Comment by rahlk** [comment]
Mention F=0.5 for BIC (Also rename BIC) #57 
- [ ] We use median not Best (both in jureczko and in config). Let's replace BIC by CG (Cluster Gradient) or GD (gradient delta).
- [ ] Make necessary changes -> B_j as something else.
