### ISSUE TITLE
dude! when are you finishing?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#59]
seriously, i have **other** things i need to be doing today

**Comment by rahlk** [comment]
I got this.. All results are in. I’m am proofreading and editing offline. 2 more hours for the first revision.

**Comment by rahlk** [comment]
- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Page 4
- [x] Page 5
- [x] Page 6
- [x] Page 7
- [ ] Page 8
- [ ] Page 9
- [ ] Page 10
- [ ] References
