### ISSUE TITLE
the other paper. ase workshop

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#60]
need to register one of use for that workshop. u r cheapest so i'll register you and get reimbused alter
- [x] are you a member of ACM or IEEE. send number - No
- [x] need an emergancy contact name: Bryan Maione
- [x] need an emergancy  phone number: +1 (717) 969 4097
- [x] need address: 215 Sterling Way, Angier NC 27501
- [x] need phone: (919) 614 6165

**Comment by timm** [comment]
what is going on here? did you send paper and register at conference? cause i was gonna register so u did not have to carry the cash flow

**Comment by rahlk** [comment]
Closed by accident.. Sorry. The deadline is Aug 31st.

**Comment by timm** [comment]
i will be on travel that day. send your details now please (so i can register you) and get the paepr off on monday

t

**Comment by timm** [comment]
any dietrary restrictions?

**Comment by rahlk** [comment]
No
