### ISSUE TITLE
when u submit, need to add in our conflicts of interest

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#61]
Laurie Williams (Chair) 
    Gerardo Canfora (PB)
   Sung Kim (PB)
    Emerson Murphy-Hill (PB)
    Nachiappan Nagappan (PB)
    Sven Apel (PC)
    Ayse Bener (PC)
    Christian Bird (PC)  
    John Grundy (PC)
    Lucas Layman (PC) 
    Robyn Lutz (PC)
    Nancy Mead (PC) 
    Tim Menzies (PC)
    Brendan Murphy (PC)
    Meiyappan Nagappan (PC)
    Linda Northrop (PC)
    Massimiliano Di Penta (PC)
       Chris Parnin (PC)
    Dan Port (PC)
    Brian Robinson (PC)
    Pete Rotella (PC)
    Abhik Roychoudhury (PC)
    Kathryn Stolee (PC)
        Paolo Tonella (PC)
    Stefan Wagner (PC)
    Tao Xie (PC)
    Dongmei Zhang (PC)
    Thomas Zimmermann (PC)

**Comment by nave91** [comment]
@timm Dr Menzies, I dont have any conflicts of interest with anyone in PC/OC (nor does my company asaik).
