### ISSUE TITLE
status? good to submit?

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#62]
please ping me first for a once over

**Comment by rahlk** [comment]
Let me do a final reread.

**Comment by rahlk** [comment]
I'm passing a copy to vivek and george to get some fresh eyes

**Comment by timm** [comment]
waiting to drink cocktails on a friday evening on your progress. 

fyi no progress = no cocktails

**Comment by rahlk** [comment]
Proof reading complete. May I upload it?

**Comment by rahlk** [comment]
Oh, Please check reference 19. Author order, is it correct?

**Comment by vivekaxl** [comment]
Author order is not correct since the paper is being referred to as Fu et
al.

On Fri, Aug 28, 2015 at 6:23 PM, Rahul Krishna notifications@github.com
wrote:

> Oh, Please check reference 19. Author order, is it correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ai-se/XTREES/issues/62#issuecomment-135901381.

## 

Regards,

Vivek Nair
Graduate Student,
Computer Science@NC State

http://vivekaxl.com

**Comment by rahlk** [comment]
PC/PB member any of us?
I know TIm Menzies (PC) and Lucas Layman (PC)

**Comment by rahlk** [comment]
Breaking for dinner. Paper's been proof read - waiting for your go ahead.

**Comment by timm** [comment]
do u know how to submit a paper?

**Comment by rahlk** [comment]
cyber chair?

**Comment by timm** [comment]
yes. from the icse16 site

ok to submit
cross fingers

did i send you the conflict of interest list?

**Comment by rahlk** [comment]
Yes.. Also, quick comment on this please ---
![image](https://cloud.githubusercontent.com/assets/1433964/9558796/1a6fe24c-4db8-11e5-9010-b9e0bc0acb03.png)

**Comment by timm** [comment]
11 only. 

do not do any others. most important

**Comment by timm** [comment]
going to dinner. will check in again in 2-3 hours. but i think we are done

**Comment by rahlk** [comment]
Cool!

**Comment by rahlk** [comment]
@timm Keywords?
I've added: Defect prediction; Configuration; Planning; Decision trees.
Please advise.

**Comment by timm** [comment]
yes
