### ISSUE TITLE
Words....

### ISSUE THREAD

**Issue by rahlk** [ai-se/XTREES#64]
![image](https://cloud.githubusercontent.com/assets/1433964/9569075/546258ac-4f2c-11e5-82a1-3022edf97c51.png)

**Comment by timm** [comment]
please update http://ai4se.net/projects/ with this (see last project)

**Comment by rahlk** [comment]
done

**Comment by timm** [comment]
Oct1 '14: Cross Trees- Visualizing Estimations using Decision Trees:
Better understanding of multi-objective optimization

with Naveen Kumar Lekkalapudi, WVU

oct14 ==> Aug15

Naveen ==> you

suppose you dropped in some of your cooler figures and added just enough text to tell people the story. what would that look like?

also, you could link them to the paper (pdf in the XTREE repo).
